################
2018-09-25 00:00
Traceback (most recent call last):
  File "c:/Users/Marcelo Muniz/Documents/GitHub/AlphaToolsIntegration/app/run.py", line 18, in <module>
    raise Exception("aiasij")
Exception: aiasij

